### ISSUE TITLE
pid параметр

### ISSUE THREAD

**Issue by boomsya** [GyverLibs/GyverPID#1]
реально нормально начинает работать при параметрах (1, 1, 1, 10)

при параметре i < 1 больше 180 градусов не набирает
при параметре d < 1 - температура плавает в районе 208-234 постоянно
параметр p - хоть 0.5, хоть 1 - не играет роли. А больше не пробовал.

**Comment by GyverLibs** [comment]
величины параметров зависят от конкретной системы, математика в регуляторе очень простая. Где то хватит 0.01 0.01, а где то нужно 1000 1000 задать

**Comment by boomsya** [comment]
решил проверить тюнер pid Cohen-Coon нагревательнй блок 3d-принтера для производства pet прутка из бутлей

```
#include "PIDtuner2.h"

#include <Wire.h> 
#include <LiquidCrystal_I2C.h>
LiquidCrystal_I2C lcd(0x27, 16, 2); //иногда адрес 0x3f

//настройка термистора
#include <thermistor.h> //установить ThermistorLibrary by Miguel Califa
thermistor therm1(A0, 0); //подключить термистор на ножку A0, 0 represents TEMP_SENSOR_0 ( configuration.h for more)
float temperature_read = 0;//текущая считанная температура

PIDtuner2 tuner;

void setup() {
  pinMode(PWM_heat_pin, OUTPUT);
  analogWrite(PWM_heat_pin, 0);

  lcd.init();
  lcd.backlight();

  tuner.setParameters(NORMAL, 0, 255, 2000, 0.5, 20);
}

void loop() {
  temperature_read = therm1.analog2temp(); //счит. температуру
  
  tuner.setInput(temperature_read);
  tuner.compute(); 
  analogWrite(PWM_heat_pin, tuner.getOutput()); 

  if (tuner.getState() == 7){
    lcd.clear();
    lcd.setCursor(0, 0);
    lcd.print(tuner.getPID_p());
    lcd.setCursor(7, 0);
    lcd.print(tuner.getPID_i());
    lcd.setCursor(0, 1);
    lcd.print(tuner.getPID_d());
    analogWrite(PWM_heat_pin, 0); 
    delay(100000);
  }
}
```
через пару минут посчитало и отобразило на дисплее:
P = -2.6 
I = 34.6
D = 0.03

что-то явно не то с алгоритмом. **P отрицательное?**

а вот такие параметрі:  tuner.setParameters(NORMAL, 0, 255, 1000, 1, 50);
дали P = -416 , I = 48, D = 36
в общем какой то бред, а не тюнинг

**Comment by boomsya** [comment]
протестил тюнер методом "реле"
`tuner.setParameters(NORMAL, 150, 40, 5000, 0.08, 6000, 50);`
но так и не получил `if (tuner.getAccuracy() > 95)` после 10 минут експериментов.
решил отобразить getAccuracy на LCD - всегда 0.

**Comment by boomsya** [comment]
в итоге построил около 30 тестов вручную и пришел к параметрам `GyverPID regulator(1, 256, 1.4, 10);`
нагреватель 40W 12V для 3d-принтера с Алиекспреса.
setpoint = 222
по факту колеблется в районе 220...228
также пробовал другие библиотеки для тюнинга (sTune к примеру) - те тоже очень сильно разное давали в итоге.

**Comment by gewisser** [comment]
> через пару минут посчитало и отобразило на дисплее:
P = -2.6
I = 34.6
D = 0.03

> что-то явно не то с алгоритмом. P отрицательное?

Я начал углубляться в расчёты и мне показались они немного подозрительными. 

Начнём с расчёта `r`

![image](https://github.com/GyverLibs/GyverPID/assets/5417292/c9061c40-258a-4775-8fb3-2b91b5eecd5f)

Тут по ссылке https://pages.mtu.edu/~tbco/cm416/cctune.html, которую указал gyver в исходном коде, есть внизу формула расчёта  `r`

![image](https://github.com/GyverLibs/GyverPID/assets/5417292/f35fea7d-2d98-4cb4-913f-3fadf7f8034a)

`r` = `tauDEL` делится на `tau`

`tauDEL` - есть разность между `t1` и `t0`

`t0` - это у нас фиксируется время, когда мы подождали устаканивание системы и врубили управляющий сигнал на максимальный указанный. На скрине ниже выделил в рамке где должно быть зафиксировано `t0`

![image](https://github.com/GyverLibs/GyverPID/assets/5417292/3a3b66c8-8bee-4734-b7b5-80b05376f106)

Но как я вижу в расчётах `t0` отсутствует. Поэтому что там в итоге будет рассчитано из PID коэф. - хз.

Я тоже словил **отрицательный P** коэффициент. Делал 10 итераций и всегда P был отрицательным.

**Comment by gewisser** [comment]
Ну и дальше tauDEL по коду отсутствует. По ходу решили, что `t0` будет близко равно к нулю и им можно пренебречь. Ну и собственно в текущей реализации тюнера он почти рассчитает всё правильно для сверх быстрых процессов. Чем более инерционный будет процесс, тем интересней будет расчёт коэффициентов :)

**Comment by gewisser** [comment]
Ещё нашел странный момент

```c++
case 3:		// ждём остывания до 1				
    if (millis() - startTime > wait) {
        startTime = millis();
        if (abs(thisValue - lastValue) < window) {
            state = 4;						
            output = (end);
        }
        lastValue = thisValue;
        debFlag = true;
    }
    break; 
```

Что происходит в коде выше? Нам надо ждать остывания системы, чтобы её перезапустить для нахождения `t2` b `t3`. Т.е. "мы должны остыть" до стартового начального показания **startValue** 
![image](https://github.com/GyverLibs/GyverPID/assets/5417292/63d5488c-045f-4851-ba69-74c40039fc16)

Мы же хотим правильно сделать расчёты? ))) Но по факту мы не ждём стартового значения на момент запуска тюнера, а просто ждём стабилизации в пределах окна и снова врубаем управляющий сигнал на максимальный указанный. 

В моей системе тюнер определяет стабильность "в моменте остывания" на уровне желтой линии на скрине ниже
![image](https://github.com/GyverLibs/GyverPID/assets/5417292/56054b83-0769-4ddf-a54f-34eccce0ef2c)


Ну соответственно дальше все расчёты идут по одному месту... Я долго не мог понять почему в дебаге видно как повисев чуть-чуть на 3 шаге сразу на 7 перелетает практически мгновенно... 

Третий case должен быть примерно такой:

``` c++
case 3:		// ждём остывания именно до начальной стартовой стабильной точки (startValue)
    if (thisValue <= startValue) {
      startTime = millis();
      state = 4;
      output = (end);
    }

    debFlag = true;

    break;
```

**Comment by boomsya** [comment]
я могу больше сказать, я так и не смог нормально подобрать все параметрі. Суть в том, что 2 библиотеки показали черти что. А оказалось что нужо дополнительно к измерениям температурі подключать фильтр. Пробовал 2 алгоритма фильтрации - все они работают нормально, главное что исчезают резкие скачки показаний и тогда PID ведет себя адекватно.
То есть я уже на 2х аппаратах где плавится пруток для принтера єто оттестил.
`temperature_read = filtered_temperature.filtered(therm1.analog2temp());`
если не юзать фильтр то через время PID вообще не контроллирует ничего так как его колбасит - представьте что у него в расчетах если показания при каждом считівании скачут от 217 до 255 градусов (условно), так как ADC в arduino плохой (у меня даже показания потенциометра читало рандомно). Как только врубаю фильтр - температура плавает в районе 220-227 при том что ожидаю получить 222 градуса.

Соответственно я понял, что все тюнинги нужно тоже проводить с фильтром, иначе в результате имеем черти что.

**Comment by gewisser** [comment]
> Соответственно я понял, что все тюнинги нужно тоже проводить с фильтром, иначе в результате имеем черти что.

Да, конечно. Все тюнинги нужно обязательно производить с фильтром, если показания шумные. 

Я пофиксил расчёты тюнера методом Cohen Coon, который у гайвера https://github.com/GyverLibs/GyverPID/blob/main/src/PIDtuner2.h + пофиксил на третьем шаге "ожидание остывания (исход к начальному состоянию)" до стартовой точки, и добавил возможность работы тюнера для инерционных систем, по типу нагрев комнаты, нагрев дома, обогрев обогревателями. 

Сейчас тестирую. Если всё ок будет, то сделаю пул реквест на слияние.

**Comment by gewisser** [comment]
В общем создал пулреквест: 

До фиксов коэффициенты были примерно такие:
> `p` -8568
`i` 25
`d` 8968

Почему примерно, потому что они сильно очень плавали и всегда `p` коэффициент был отрицательным. Как будто под капотом какой рандомный алгоритм работал ))

После правок, и так же несколько прогонов тюнера, коэффициенты стали такими:
> `p` 20
`i` -0.0001
`d` 6856

Отрицательного коэффициента `p` - больше не появлялось
И эти коэффициенты после внесения правок прям собственно попали почти в точку. 
Чуть пришлось поднять `p` и `i`

**Comment by boomsya** [comment]
ну что же. проверю по возможности. Ну и еще раз прогоню sTune с фильтром
